services:
  db:
    image: postgres
    container_name: LOC_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD:${PG_PASS}
      POSTGRES_DB: LOC_search
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
